language: php

php:
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.3' ]]; then vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '7.3' ]]; then vendor/bin/phpunit --verbose; fi

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.3' ]]; then vendor/bin/php-coveralls -v --coverage_clover build/logs/clover.xml; fi
