language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - hhvm

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
matrix:
  allow_failures:
    - php: hhvm

install:
  - composer install --prefer-source

script: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - vendor/bin/php-coveralls --coverage_clover build/logs/clover.xml
